package com.yingxs.it.shunfengkuaidi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-24T20:07:52.443+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://shunFengKuaiDi.it.yingxs.com/", name = "AddressInfoI")
@XmlSeeAlso({ObjectFactory.class})
public interface AddressInfoI {

    @WebMethod
    @Action(input = "http://shunFengKuaiDi.it.yingxs.com/AddressInfoI/getAdressInfoByUserIdRequest", output = "http://shunFengKuaiDi.it.yingxs.com/AddressInfoI/getAdressInfoByUserIdResponse")
    @RequestWrapper(localName = "getAdressInfoByUserId", targetNamespace = "http://shunFengKuaiDi.it.yingxs.com/", className = "com.yingxs.it.shunfengkuaidi.GetAdressInfoByUserId")
    @ResponseWrapper(localName = "getAdressInfoByUserIdResponse", targetNamespace = "http://shunFengKuaiDi.it.yingxs.com/", className = "com.yingxs.it.shunfengkuaidi.GetAdressInfoByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAdressInfoByUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
